services:
  scraper-service:
    build: .
    container_name: scraper_b2b_construccion
    ports: 
      - "8000:8000"
    env_file: 
      - .env
    volumes: 
      - ./ETL_scraper:/app/scraper
    restart: unless-stopped

networks:
  default:
    name: plataforma_construccion_net
    external: true